### ISSUE TITLE
Train ChatterBot with FAQ YAML file

### ISSUE THREAD

**Issue by mygenel** [drexelai/isss-chatbot#1]
Example file is: https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/conversations.yml

**Comment by dsbuddy** [comment]
This is basically the same as the other task. The only thing we need to do is create the conversation file and then add it to the ChatterBot. That's it

**Comment by ya332** [comment]
Do you mean same as issue#1?

**Comment by dsbuddy** [comment]
Issue 1 and Issue 3 are inherently the same thing.
We need to:

- Convert FAQ to YAML
- Create Chatterbot with YAML above

Then we have a chatbot

**Comment by ya332** [comment]
This issue depends on the creation of YAML file. Please see issue #3

**Comment by ya332** [comment]
Initial training is completed
