### ISSUE TITLE
Convert FAQ corpus to YAML file

### ISSUE THREAD

**Issue by ya332** [drexelai/isss-chatbot#3]
Some feasible ways of doing this:

- Copy paste

- Cheerio(js)

- scrapy(python)

- requests for performing your HTTP requests

- BeautifulSoup4 for handling all of your HTML processing

**Comment by quanglddev** [comment]
You mean we are converting the content (in any means possible) from this website: [FREQUENTLY ASKED QUESTIONS](https://drexel.edu/undergrad/apply/int-instructions/faq/) to an Excel document?

**Comment by ya332** [comment]
We would convert the content from the FAQ website to this yml file:

https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/conversations.yml

**Comment by quanglddev** [comment]
May I ask for the deadline?

**Comment by ya332** [comment]
Deadline would be September 21st.

**Comment by quanglddev** [comment]
I believe this is _partially_ solved with the python scraper script.

**Comment by ya332** [comment]
Closing the issue..
